name: Update gist with WakaTime stats
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5b31a1f5db6308bdac8ce75d87987412
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
